# Splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

# Cheatsheet
unbind ?
bind ? display-popup -E -w 60% -h 40% \
  "fzf \
    --no-multi \
    --layout=reverse \
    --info=hidden \
    --prompt='' \
    --ghost='Keybindings... ' \
    --pointer='›' \
    --gutter=' ' \
    --color='bg+:-1,gutter:-1' \
    < ~/.config/tmux/data/tmux-cheatsheet"
