-- Imports
require("config.theme")
require("config.treesitter")
require("config.lsp")
require("config.mason")
require("config.autopairs")
require("config.completion")
require("config.lualine")
require("config.incline")
require("config.gitsigns")
require("config.diffview")
